[workspace]
name = "topograph"
description = "Topological analysis on graphs and networks."
version = "0.0.1"
channels = ['conda-forge']
platforms = ['osx-arm64']
preview = ["pixi-build"]

[dependencies]
python = "~=3.10.0"
pytest = "*"
ruff = "*"
pip = "*"

[tasks]
version = "topograph version"
completion = "topograph --install-completion"
shoot = "topograph gun shoot"
load = "topograph gun load"

[pypi-dependencies]
python-dotenv = "*"
rich = "*"
typer = "*"
topograph = { path = ".", editable = true }

[package]
name = "topograph"
version = "0.0.1"

[package.build] 
backend = { name = "pixi-build-python", version = "0.4.*" }

[package.host-dependencies] 
hatchling = "*"

[package.build-dependencies]
hatchling = "*"

[package.run-dependencies]
rich = "*"
typer = "*"
